#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Dec 20 11:54:32 UTC 2023
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim tb_fifo_reg_time_synth -key {Post-Synthesis:sim_1:Timing:tb_fifo_reg} -tclbatch tb_fifo_reg.tcl -protoinst "protoinst_files/ground_port.protoinst" -log simulate.log"
xsim tb_fifo_reg_time_synth -key {Post-Synthesis:sim_1:Timing:tb_fifo_reg} -tclbatch tb_fifo_reg.tcl -protoinst "protoinst_files/ground_port.protoinst" -log simulate.log

