/cad/Siemens/2022-23/RHELx86/QUESTA-CORE-PRIME_2022.4/questasim/bin/vlib /home/azafeer/Desktop/test/reg_sim/reg_sim.cache/compile_simlib/questa/common_rpc_v1
/cad/Siemens/2022-23/RHELx86/QUESTA-CORE-PRIME_2022.4/questasim/bin/vmap common_rpc_v1 /home/azafeer/Desktop/test/reg_sim/reg_sim.cache/compile_simlib/questa/common_rpc_v1
/tool/gcc/7.4.0/bin/g++  -c -fPIC -I /cad/xilinx/Vivado/2023.2/data/simmodels/questa/2022.4/lnx64/7.4.0/ext/protobuf/include -I /cad/xilinx/Vivado/2023.2/data/systemc/simlibs/common_rpc/common_rpc_v1/include -I /cad/xilinx/Vivado/2023.2/tps/boost_1_72_0 -Wall -fPIC -fPIC -std=c++11 /cad/xilinx/Vivado/2023.2/data/systemc/simlibs/common_rpc/common_rpc_v1/src/debug_manager.cpp -o /home/azafeer/Desktop/test/reg_sim/reg_sim.cache/compile_simlib/questa/common_rpc_v1/debug_manager.o
/tool/gcc/7.4.0/bin/g++  -c -fPIC -I /cad/xilinx/Vivado/2023.2/data/simmodels/questa/2022.4/lnx64/7.4.0/ext/protobuf/include -I /cad/xilinx/Vivado/2023.2/data/systemc/simlibs/common_rpc/common_rpc_v1/include -I /cad/xilinx/Vivado/2023.2/tps/boost_1_72_0 -Wall -fPIC -fPIC -std=c++11 /cad/xilinx/Vivado/2023.2/data/systemc/simlibs/common_rpc/common_rpc_v1/src/rpc_messages.pb.cpp -o /home/azafeer/Desktop/test/reg_sim/reg_sim.cache/compile_simlib/questa/common_rpc_v1/rpc_messages.pb.o
/tool/gcc/7.4.0/bin/g++  -c -fPIC -I /cad/xilinx/Vivado/2023.2/data/simmodels/questa/2022.4/lnx64/7.4.0/ext/protobuf/include -I /cad/xilinx/Vivado/2023.2/data/systemc/simlibs/common_rpc/common_rpc_v1/include -I /cad/xilinx/Vivado/2023.2/tps/boost_1_72_0 -Wall -fPIC -fPIC -std=c++11 /cad/xilinx/Vivado/2023.2/data/systemc/simlibs/common_rpc/common_rpc_v1/src/xaxi_accel_profiler.cpp -o /home/azafeer/Desktop/test/reg_sim/reg_sim.cache/compile_simlib/questa/common_rpc_v1/xaxi_accel_profiler.o
/tool/gcc/7.4.0/bin/g++  -c -fPIC -I /cad/xilinx/Vivado/2023.2/data/simmodels/questa/2022.4/lnx64/7.4.0/ext/protobuf/include -I /cad/xilinx/Vivado/2023.2/data/systemc/simlibs/common_rpc/common_rpc_v1/include -I /cad/xilinx/Vivado/2023.2/tps/boost_1_72_0 -Wall -fPIC -fPIC -std=c++11 /cad/xilinx/Vivado/2023.2/data/systemc/simlibs/common_rpc/common_rpc_v1/src/xaxi_accel_profiler_instmgr.cpp -o /home/azafeer/Desktop/test/reg_sim/reg_sim.cache/compile_simlib/questa/common_rpc_v1/xaxi_accel_profiler_instmgr.o
/tool/gcc/7.4.0/bin/g++  -c -fPIC -I /cad/xilinx/Vivado/2023.2/data/simmodels/questa/2022.4/lnx64/7.4.0/ext/protobuf/include -I /cad/xilinx/Vivado/2023.2/data/systemc/simlibs/common_rpc/common_rpc_v1/include -I /cad/xilinx/Vivado/2023.2/tps/boost_1_72_0 -Wall -fPIC -fPIC -std=c++11 /cad/xilinx/Vivado/2023.2/data/systemc/simlibs/common_rpc/common_rpc_v1/src/xaxi_profiler.cpp -o /home/azafeer/Desktop/test/reg_sim/reg_sim.cache/compile_simlib/questa/common_rpc_v1/xaxi_profiler.o
/tool/gcc/7.4.0/bin/g++  -c -fPIC -I /cad/xilinx/Vivado/2023.2/data/simmodels/questa/2022.4/lnx64/7.4.0/ext/protobuf/include -I /cad/xilinx/Vivado/2023.2/data/systemc/simlibs/common_rpc/common_rpc_v1/include -I /cad/xilinx/Vivado/2023.2/tps/boost_1_72_0 -Wall -fPIC -fPIC -std=c++11 /cad/xilinx/Vivado/2023.2/data/systemc/simlibs/common_rpc/common_rpc_v1/src/xaxi_profiler_instmgr.cpp -o /home/azafeer/Desktop/test/reg_sim/reg_sim.cache/compile_simlib/questa/common_rpc_v1/xaxi_profiler_instmgr.o
/tool/gcc/7.4.0/bin/g++  -c -fPIC -I /cad/xilinx/Vivado/2023.2/data/simmodels/questa/2022.4/lnx64/7.4.0/ext/protobuf/include -I /cad/xilinx/Vivado/2023.2/data/systemc/simlibs/common_rpc/common_rpc_v1/include -I /cad/xilinx/Vivado/2023.2/tps/boost_1_72_0 -Wall -fPIC -fPIC -std=c++11 /cad/xilinx/Vivado/2023.2/data/systemc/simlibs/common_rpc/common_rpc_v1/src/xaxi_stream_profiler.cpp -o /home/azafeer/Desktop/test/reg_sim/reg_sim.cache/compile_simlib/questa/common_rpc_v1/xaxi_stream_profiler.o
/tool/gcc/7.4.0/bin/g++  -c -fPIC -I /cad/xilinx/Vivado/2023.2/data/simmodels/questa/2022.4/lnx64/7.4.0/ext/protobuf/include -I /cad/xilinx/Vivado/2023.2/data/systemc/simlibs/common_rpc/common_rpc_v1/include -I /cad/xilinx/Vivado/2023.2/tps/boost_1_72_0 -Wall -fPIC -fPIC -std=c++11 /cad/xilinx/Vivado/2023.2/data/systemc/simlibs/common_rpc/common_rpc_v1/src/xaxi_stream_profiler_instmgr.cpp -o /home/azafeer/Desktop/test/reg_sim/reg_sim.cache/compile_simlib/questa/common_rpc_v1/xaxi_stream_profiler_instmgr.o
/tool/gcc/7.4.0/bin/g++  -c -fPIC -I /cad/xilinx/Vivado/2023.2/data/simmodels/questa/2022.4/lnx64/7.4.0/ext/protobuf/include -I /cad/xilinx/Vivado/2023.2/data/systemc/simlibs/common_rpc/common_rpc_v1/include -I /cad/xilinx/Vivado/2023.2/tps/boost_1_72_0 -Wall -fPIC -fPIC -std=c++11 /cad/xilinx/Vivado/2023.2/data/systemc/simlibs/common_rpc/common_rpc_v1/src/debug_manager_if.cxx -o /home/azafeer/Desktop/test/reg_sim/reg_sim.cache/compile_simlib/questa/common_rpc_v1/debug_manager_if.o
/tool/gcc/7.4.0/bin/g++  -c -fPIC -I /cad/xilinx/Vivado/2023.2/data/simmodels/questa/2022.4/lnx64/7.4.0/ext/protobuf/include -I /cad/xilinx/Vivado/2023.2/data/systemc/simlibs/common_rpc/common_rpc_v1/include -I /cad/xilinx/Vivado/2023.2/tps/boost_1_72_0 -Wall -fPIC -fPIC -std=c++11 /cad/xilinx/Vivado/2023.2/data/systemc/simlibs/common_rpc/common_rpc_v1/src/msg_handler.cxx -o /home/azafeer/Desktop/test/reg_sim/reg_sim.cache/compile_simlib/questa/common_rpc_v1/msg_handler.o
/tool/gcc/7.4.0/bin/g++  -c -fPIC -I /cad/xilinx/Vivado/2023.2/data/simmodels/questa/2022.4/lnx64/7.4.0/ext/protobuf/include -I /cad/xilinx/Vivado/2023.2/data/systemc/simlibs/common_rpc/common_rpc_v1/include -I /cad/xilinx/Vivado/2023.2/tps/boost_1_72_0 -Wall -fPIC -fPIC -std=c++11 /cad/xilinx/Vivado/2023.2/data/systemc/simlibs/common_rpc/common_rpc_v1/src/msg_handler_impl.cxx -o /home/azafeer/Desktop/test/reg_sim/reg_sim.cache/compile_simlib/questa/common_rpc_v1/msg_handler_impl.o
/tool/gcc/7.4.0/bin/g++  -c -fPIC -I /cad/xilinx/Vivado/2023.2/data/simmodels/questa/2022.4/lnx64/7.4.0/ext/protobuf/include -I /cad/xilinx/Vivado/2023.2/data/systemc/simlibs/common_rpc/common_rpc_v1/include -I /cad/xilinx/Vivado/2023.2/tps/boost_1_72_0 -Wall -fPIC -fPIC -std=c++11 /cad/xilinx/Vivado/2023.2/data/systemc/simlibs/common_rpc/common_rpc_v1/src/sk_client.cxx -o /home/azafeer/Desktop/test/reg_sim/reg_sim.cache/compile_simlib/questa/common_rpc_v1/sk_client.o
/tool/gcc/7.4.0/bin/g++  -c -fPIC -I /cad/xilinx/Vivado/2023.2/data/simmodels/questa/2022.4/lnx64/7.4.0/ext/protobuf/include -I /cad/xilinx/Vivado/2023.2/data/systemc/simlibs/common_rpc/common_rpc_v1/include -I /cad/xilinx/Vivado/2023.2/tps/boost_1_72_0 -Wall -fPIC -fPIC -std=c++11 /cad/xilinx/Vivado/2023.2/data/systemc/simlibs/common_rpc/common_rpc_v1/src/unix_socket.cxx -o /home/azafeer/Desktop/test/reg_sim/reg_sim.cache/compile_simlib/questa/common_rpc_v1/unix_socket.o
