######################################################################
#
# File name : tb_fifo_reg_wave.do
# Created on: Fri Jan 19 19:22:37 UTC 2024
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
