######################################################################
#
# File name : tb_fifo_reg.udo
# Created on: Fri Jan 19 19:22:37 UTC 2024
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
