######################################################################
#
# File name : tb_fifo_reg_compile.do
# Created on: Fri Feb 02 15:27:30 UTC 2024
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
/cad/mentor/questasim_2019.4/questasim/bin/vlib questa_lib/work
/cad/mentor/questasim_2019.4/questasim/bin/vlib questa_lib/msim

/cad/mentor/questasim_2019.4/questasim/bin/vlib questa_lib/msim/xil_defaultlib

/cad/mentor/questasim_2019.4/questasim/bin/vmap xil_defaultlib questa_lib/msim/xil_defaultlib

/cad/mentor/questasim_2019.4/questasim/bin/vlog -64 -incr -mfcu -work xil_defaultlib  \
"tb_fifo_reg_func_synth.v" \

/cad/mentor/questasim_2019.4/questasim/bin/vlog -64 -incr -mfcu -sv -work xil_defaultlib  \
"../../../../../../FIFO/FIFO.srcs/sim_1/new/tb_fifo_reg.sv" \


