######################################################################
#
# File name : tb_fifo_reg_simulate.do
# Created on: Fri Feb 02 15:27:32 UTC 2024
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
vsim -lib xil_defaultlib tb_fifo_reg_opt

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_fifo_reg_wave.do}

view wave
view structure
view signals

do {tb_fifo_reg.udo}

run 1000ns
