######################################################################
#
# File name : tb_fifo_reg_elaborate.do
# Created on: Fri Feb 02 15:27:31 UTC 2024
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
/cad/mentor/questasim_2019.4/questasim/bin/vopt -64 +acc=npr -suppress 10016 -L xil_defaultlib -L unisims_ver -L secureip -work xil_defaultlib xil_defaultlib.tb_fifo_reg xil_defaultlib.glbl -o tb_fifo_reg_opt
