#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2023.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Feb 20 20:31:24 UTC 2024
# SW Build 4029153 on Fri Oct 13 20:13:54 MDT 2023
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_small_reg_top_func_synth -key {Post-Synthesis:sim_1:Functional:tb_small_reg_top} -tclbatch tb_small_reg_top.tcl -view /home/azafeer/Desktop/test/reg_sim/tb_fifo_reg_func_synth_test_1.wcfg -log simulate.log"
xsim tb_small_reg_top_func_synth -key {Post-Synthesis:sim_1:Functional:tb_small_reg_top} -tclbatch tb_small_reg_top.tcl -view /home/azafeer/Desktop/test/reg_sim/tb_fifo_reg_func_synth_test_1.wcfg -log simulate.log

